### ISSUE TITLE
Problems with 2 wavelengths and 2 datafiles with LaB6

### ISSUE THREAD

**Issue by PaoloScardi** [WONDER-project/Orange3-WONDER-Prototype#10]
Sembra non gestire correttamente le Kalpha. Oltre a rifinirle separatamente, è possibile legare tra loro le Kalpha2 ? Immagino di si usando f(x).
[TwoLaB6filesTwoWavelengths.zip](https://github.com/WONDER-project/Orange3-WONDER/files/2067312/TwoLaB6filesTwoWavelengths.zip)

**Comment by lucarebuffi** [comment]
Ho risolto. Versione 0.1.19
![screen shot 2018-06-04 at 12 52 33](https://user-images.githubusercontent.com/6713598/40913880-6a81c966-67f6-11e8-8306-0e91548ab45f.png)
![screen shot 2018-06-04 at 12 52 37](https://user-images.githubusercontent.com/6713598/40913882-6c62f1e2-67f6-11e8-9072-8e4aa56ccf7b.png)

**Comment by PaoloScardi** [comment]
Corretto, adesso funziona
