### ISSUE TITLE
Lorentz-Polarization

### ISSUE THREAD

**Issue by PaoloScardi** [WONDER-project/Orange3-WONDER-Prototype#11]
Va fatto qualcosa per il LP. Dal controllo sembra a momento sia pari a 1/(s*s_hkl), generalmente corretto con l'attenzione di non andare ad angoli troppo bassi (vedi allegato). Ma va considerato che quasi sempre c'e' un monocromatore e la polarizzazione non puo' essere assunta pari a 1. Qui in allegato cosa occorre fare, in sostanza prevedere il termine del monocromatore (un angolo, di solito fisso, specificato dall'utente in base allo strumento usato, radiazione e tipo di cristallo).
Questo termine comporta un cos, e quindi spazio 2theta?
[LPfactor.zip](https://github.com/WONDER-project/Orange3-WONDER/files/2068054/LPfactor.zip)

**Comment by lucarebuffi** [comment]
Lo so bene, ma si era d'accordo di lasciare la sua implementazione completa a un momento successivo.

**Comment by PaoloScardi** [comment]
ok, certo, solo che cosi' non si puo' testare il modello strutturale se non su dati da sincrotrone. Non e' urgente, ma bene saperlo

**Comment by lucarebuffi** [comment]
ASAP

**Comment by lucarebuffi** [comment]
Fatto: Versione 0.1.20
