### ISSUE TITLE
Test case

### ISSUE THREAD

**Issue by PaoloScardi** [WONDER-project/Orange3-WONDER-Prototype#12]
Here is a zip with a good case to test Wonder - in particular the structural model

[Topas6_projects.zip](https://github.com/WONDER-project/Orange3-WONDER/files/2079231/Topas6_projects.zip)

**Comment by PaoloScardi** [comment]
[WonderFe_TestCase.zip](https://github.com/WONDER-project/Orange3-WONDER/files/2079366/WonderFe_TestCase.zip)

Here is the current file used in Wonder

**Comment by PaoloScardi** [comment]
Temo ci sia un problema di Lorentz che diverge in 2theta=0.
In realta' questa divergenza su cura sommando un picco negativo centrato in -s_hkl (come in un articolo di Patterson 1939, rigoroso per sfera, approssimato per altri profili). Altrimenti - non grave, è quello che fa TOPAS e tanti altri software, usiamo Lorentz = 1/(s_hkl^2) e il problema sparisce.
Questa problematica è descritta nel paper qui allegato (lo aggiungo qui solo per completezza)


[zkri.2011.1448.pdf](https://github.com/WONDER-project/Orange3-WONDER/files/2080069/zkri.2011.1448.pdf)


![image](https://user-images.githubusercontent.com/33222119/41094975-56f4d10c-6a50-11e8-8b7c-d1a74df121bc.png)

**Comment by lucarebuffi** [comment]
PM2K come fa?

**Comment by PaoloScardi** [comment]
Cosi' come dicevo. Credo ci sia una modalità 'Patterson', che quando attivata permette di usare 1/(s*s_hkl), perchè 'cura' la divergenza 1/s a s=0. E poi una modalità normale dove è probabile si usi 1/(s_hkl^2). Per ora terrei buono quest'ultimo, 1/(s_hkl^2) che non ha proprio la divergenza (indipendente da s).

**Comment by lucarebuffi** [comment]
Ok, questo si può implementarlo subito

**Comment by lucarebuffi** [comment]
Corretto con formula approssimata in 0.1.22
