### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by PaoloScardi** [WONDER-project/Orange3-WONDER-Prototype#14]
In wppm_functions, line 661, a common error in the atomic scattering factor the variable is not s but s/2, that is, instead of
        f_s += a*numpy.exp(-b*(s_angstrom**2))
it should be 
        f_s += a*numpy.exp(-b*(0.5*s_angstrom)**2)

**Comment by lucarebuffi** [comment]
Fixed in 0.1.23
