### ISSUE TITLE
LaB6 with 10 files

### ISSUE THREAD

**Issue by PaoloScardi** [WONDER-project/Orange3-WONDER-Prototype#20]
some problems with 10 data files.
It would be necessary to allow refinement of the sample alpha2 fraction (and other spectral components if it is the case)  with all data files. Alternative is to refine this parameter independently with each data file and then the user can calculate manually the mean value to use with data analysis with the refined Instrumental Profile

**Comment by lucarebuffi** [comment]
Bug fixed in 0.1.39
