### ISSUE TITLE
Wavelengths

### ISSUE THREAD

**Issue by PaoloScardi** [WONDER-project/Orange3-WONDER-Prototype#4]
Esempio 'lam' di Topas, descrizione CuKalpha con 2 componenti soltanto (Kalpha1 e Kalpha2)

   lam
      ymin_on_ymax 0.0001 
      la 0.653817 lo 1.540596  lh 0.501844
      la 0.346183 lo 1.544493  lh 0.626579
      
' ymin_on_ymax 0.0001 : con questo Topas stabilisce la soglia di intensità sotto la quale tronca il picco
' ovvero quando l'intensità va sotto 0.0001 del massimo
' la è l'intensità relativa della componente
' lo è la lunghezza d'onda in Angstrom
' lh è la larghezza della corrispondente linea di emissione; a noi al momento non serve, chissà, in futuro
' la e lo dovrebbero entrambi essere parametri rifinibili (variabili) per ottimizzarli su un dato strumento

[CoKa3.lam.txt](https://github.com/WONDER-project/Orange3-WONDER/files/2000261/CoKa3.lam.txt)
[CrKb5_Holzer.lam.txt](https://github.com/WONDER-project/Orange3-WONDER/files/2000262/CrKb5_Holzer.lam.txt)
[CuKa2.lam.txt](https://github.com/WONDER-project/Orange3-WONDER/files/2000263/CuKa2.lam.txt)
[CuKa5.lam.txt](https://github.com/WONDER-project/Orange3-WONDER/files/2000264/CuKa5.lam.txt)
[MoKa2.lam.txt](https://github.com/WONDER-project/Orange3-WONDER/files/2000265/MoKa2.lam.txt)

**Comment by lucarebuffi** [comment]
I file sono stati inglobati direttamente dentro l'applicazione. I valori (lunghezze e pesi) vengono proposti a video come costanti
