### ISSUE TITLE
Test new release 0.1.5

### ISSUE THREAD

**Issue by PaoloScardi** [WONDER-project/Orange3-WONDER-Prototype#5]
Funziona. Direi bene, logico e facile da capire.
Ma dal confronto con PM2K, di cui allego i file per una sessione basata su 4 picchi LaB6 raccolti con MCX (tuoi dati), risulta che PM2K va giu' ad una WSS quasi di meta' e fitta nmeglio.... eppure mi sembra tutto uguale. Un baco?

Seguono file

**Comment by lucarebuffi** [comment]
[Test_0.1.5.zip](https://github.com/WONDER-project/Orange3-WONDER/files/2044236/Test_0.1.5.zip)

**Comment by lucarebuffi** [comment]
Chiuso: con adeguato campionamento dello spazio dove viene eseguita la trasformata di Fourier i risultati coincidono.
