### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by PaoloScardi** [WONDER-project/Orange3-WONDER-Prototype#7]
Problema in installazione 0.1.15. provo a disinstallare e fa lo stesso:

![image](https://user-images.githubusercontent.com/33222119/40887888-9a40710e-674f-11e8-8eab-7b777f9401e2.png)

![image](https://user-images.githubusercontent.com/33222119/40887889-a456bc5c-674f-11e8-810b-c57c9b2ae3d7.png)

**Comment by PaoloScardi** [comment]
Reinstallato tutto il problema sembra scomparso...boh?

**Comment by lucarebuffi** [comment]
Welcome to the microsoft world.....
