### ISSUE TITLE
Testing structural model...

### ISSUE THREAD

**Issue by PaoloScardi** [WONDER-project/Orange3-WONDER-Prototype#8]
![image](https://user-images.githubusercontent.com/33222119/40888068-1f404c60-6752-11e8-9881-fad0f1dd593b.png)

Succede mentre con FeMo uso structural model e LP. Il resto come nei test precedenti

**Comment by lucarebuffi** [comment]
Per abitudine allega il file che stai usando, altrimenti non posso fare assolutamente nulla.

**Comment by lucarebuffi** [comment]
Il modello strutturale è ancora tutto da verificare  e controllare, penso sia meglio prima vi riguardate tutte le formule utilizzate nel file wppm_functions.pyx, altrimenti diventa difficile eseguire dei test.

**Comment by PaoloScardi** [comment]
okay. vedo che il fattore di struttura è calcolato ogni volta. Piuttosto uno spreco visto che finora, di fatto, usiamo un modello a 1 solo elemento, ovvero sc, bcc, fcc di metalli (singoli elementi). Un calcolo di fattore di struttura fatto ogni volta usando posizioni atomiche, fase e modulo quadro ha forse senso se/quando implementiamo la possibilità di avere modelli strutturali per strutture con piu' specie atomiche come CaF2, CeO2, ottima cosa, ma di la' da venire. Per adesso |F|^2 è f^2 per sc, 4*f^2 per bcc e 16*f^2 per fcc. In pratica, il termine strutturale è molteplicità x f^2 (f è il fattore di scattering atomico, eventualmente corretto per i Deltaf' e i*Deltaf''

**Comment by lucarebuffi** [comment]
Meglio mettere una if, non butto via tutto se è corretto.

**Comment by PaoloScardi** [comment]
no certo, ma non so se quello che c'e' adesso è corretto: dovrebbe dare sempre un valore costante, 1, 4, 16 come |F|^2 (a meno dell'f). Eventualmente domani controllo con Alberto

**Comment by lucarebuffi** [comment]
Ok, appena possibile implemento il modello semplificato (x patterns da un solo elemento cubico)

**Comment by lucarebuffi** [comment]
0.1.18
